CONVERT_TO=rp2040_ce
VIA_ENABLE          = yes
VIAL_ENABLE         = yes
LTO_ENABLE          = yes
RGBLIGHT_ENABLE     = no
RGB_MATRIX_ENABLE   = yes # Can't have RGBLIGHT and RGB_MATRIX at the same time.
RGB_MATRIX_CUSTOM_USER = yes
VIALRGB_ENABLE      = yes
MOUSEKEY_ENABLE     = yes
OLED_ENABLE         = yes
WPM_ENABLE = yes
#OLED_DRIVER         = SSD1306
EXTRAKEY_ENABLE     = yes
COMBO_ENABLE        = yes
QMK_SETTINGS        = yes
